[project]
name = "nbv-gym"
description = "Next Best View Selection Techniques for Radiance Fields"
version = "0.1.0"

[tool.setuptools.packages.find]
include = ["nbv_gym*"]

# register the entry point of your new method here:
[project.entry-points.'nerfstudio.method_configs']
nbv-splat = 'nbv_gym.config:nbv_splat'
