[project]
name = "shadow-splat"
description = "Shadow Gaussian Splatting"
version = "0.1.0"

[tool.setuptools.packages.find]
include = ["shadow_splat*"]

# register the entry point of your new method here:
[project.entry-points.'nerfstudio.method_configs']
shadow-splat = 'shadow_splat.config:shadow_splat'
# shadow-splat-2dgs = 'shadow_splat.config:shadow_splat_2dgs'

[project.entry-points.'nerfstudio.dataparser_configs']
shadow-splat-data = 'shadow_splat.dataparser_config:shadow_splat_dataparser'
