method:
  name: 3dgs_coverage

data:
  # either a single path here OR a list under 'dirs' below
  data_dir: "~/StanfordMSL/LL-Baselines/vista/nerf_data/plane"
  # optional: override the list used in __main__
  # dirs:
  #   - { data_dir: "~/StanfordMSL/LL-Baselines/vista/nerf_data/plane" }
  train_fraction: 0.8
  k_init_neighbors: 10

incremental:
  num_data_aug_steps: 50

training:
  num_train_iterations: 1000
  load_from_checkpoint: true
  load_from_checkpoint_initial: false
  initial_checkpoint_file: null

planner:
  root_index: 0
  num_nearest_neighbors_for_querying_uncertainty: 5
  num_poses_to_add_per_augmentation_step: 5
  intrinsics_scale: 0.25

rendering:
  save_rendered_images: false
  save_render_selected_best_pose: false

output:
  root: ""   # leave blank to use script default

runtime:
  view_cached_results: false
